# Generated manually for Controller's initial schema.
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Livery', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('bustimes_id', models.PositiveIntegerField(unique=True)), ('name', models.CharField(max_length=255)), ('left_css', models.TextField(blank=True)), ('right_css', models.TextField(blank=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='Operator', fields=[('noc', models.CharField(max_length=16, primary_key=True, serialize=False)), ('slug', models.SlugField(blank=True, max_length=120)), ('name', models.CharField(max_length=255)), ('region_id', models.CharField(blank=True, max_length=12)), ('vehicle_mode', models.CharField(default='bus', max_length=20)), ('raw_data', models.JSONField(blank=True, default=dict)), ('updated_at', models.DateTimeField(auto_now=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='VehicleType', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('bustimes_id', models.PositiveIntegerField(unique=True)), ('name', models.CharField(max_length=255)), ('fuel', models.CharField(blank=True, max_length=40)), ('style', models.CharField(blank=True, max_length=80)), ('double_decker', models.BooleanField(default=False)), ('coach', models.BooleanField(default=False)), ('electric', models.BooleanField(default=False))], options={'ordering': ['name']}),
        migrations.CreateModel(name='Service', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('bustimes_id', models.PositiveIntegerField(unique=True)), ('slug', models.SlugField(max_length=255)), ('line_name', models.CharField(max_length=80)), ('description', models.CharField(blank=True, max_length=500)), ('mode', models.CharField(blank=True, max_length=30)), ('raw_data', models.JSONField(blank=True, default=dict)), ('updated_at', models.DateTimeField(auto_now=True)), ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='alerts.operator'))], options={'ordering': ['line_name', 'description']}),
        migrations.CreateModel(name='Vehicle', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('bustimes_id', models.PositiveIntegerField(unique=True)), ('slug', models.SlugField(max_length=255)), ('fleet_number', models.CharField(blank=True, max_length=80)), ('fleet_code', models.CharField(blank=True, max_length=80)), ('reg', models.CharField(blank=True, max_length=32)), ('branding', models.CharField(blank=True, max_length=255)), ('garage_name', models.CharField(blank=True, max_length=255)), ('withdrawn', models.BooleanField(default=False)), ('raw_data', models.JSONField(blank=True, default=dict)), ('updated_at', models.DateTimeField(auto_now=True)), ('livery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.livery')), ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='alerts.operator')), ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.vehicletype'))], options={'ordering': ['fleet_number', 'reg']}),
        migrations.CreateModel(name='Rule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=160)), ('active', models.BooleanField(default=True)), ('fuels', models.JSONField(blank=True, default=list)), ('custom_lines', models.JSONField(blank=True, default=list)), ('new_vehicle', models.BooleanField(default=False)), ('vehicle_change', models.BooleanField(default=False)), ('new_service', models.BooleanField(default=False)), ('website_alert', models.BooleanField(default=True)), ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('urgent', 'Urgent')], default='info', max_length=12)), ('discord_alert', models.BooleanField(default=False)), ('discord_webhook', models.URLField(blank=True)), ('quietly_log', models.BooleanField(default=False)), ('alert_once', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('liveries', models.ManyToManyField(blank=True, to='alerts.livery')), ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='alerts.operator')), ('services', models.ManyToManyField(blank=True, to='alerts.service')), ('vehicle_types', models.ManyToManyField(blank=True, to='alerts.vehicletype')), ('vehicles', models.ManyToManyField(blank=True, to='alerts.vehicle'))], options={'ordering': ['-active', 'name']}),
        migrations.CreateModel(name='PollState', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('vehicles_snapshot', models.JSONField(blank=True, default=dict)), ('services_snapshot', models.JSONField(blank=True, default=dict)), ('last_fleet_poll', models.DateTimeField(blank=True, null=True)), ('last_tracking_poll', models.DateTimeField(blank=True, null=True)), ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll_state', to='alerts.operator'))]),
        migrations.CreateModel(name='AlertEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('severity', models.CharField(default='info', max_length=12)), ('event_type', models.CharField(max_length=40)), ('title', models.CharField(max_length=255)), ('detail', models.TextField(blank=True)), ('payload', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)), ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.operator')), ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='alerts.rule'))], options={'ordering': ['-created_at']}),
    ]
