# Generated by Django 5.2.17 on 2026-08-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='region_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
